name: GitHub Actions Zip
on:   
  release:
    types:
      - created
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Create ankiaddon
        run: zip -r -q breakdance-woo-search.zip .
